name: Build Flet macOS App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest # Используем виртуальную машину macOS

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet pyinstaller

      - name: Build macOS App
        run: |
          # В macOS разделитель в --add-data это двоеточие (:) вместо точки с запятой (;)
          flet pack main.py --icon icon.icns --name "KroneckerApp" --add-data "examples.json:."

      - name: Archive App Bundle
        run: |
          # macOS приложения — это папки .app. Для скачивания их нужно упаковать в zip.
          cd dist
          zip -r ../KroneckerApp_macOS.zip KroneckerApp.app

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: KroneckerApp_macOS.zip